model_type: "yolo12n"

batch_size: 16
img_size: 1920
epochs: 50
learning_rate: 0.001
momentum: 0.937
weight_decay: 0.0005
pretrained_weights: "yolo12n.pt"

train: ../train/images
val: ../valid/images
test: ../test/images

nc: 1
names: ['matricula']

roboflow:
  workspace: vc
  project: matriculas-espanolas
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/vc/matriculas-espanolas/dataset/1